// react/src/components/auth/auth-container.tsx
import React, { useState } from "react";
import Login from "./login";
import Register from "./register";

interface AuthContainerProps {
  onAuthSuccess: () => void;
}

export const AuthContainer: React.FC<AuthContainerProps> = ({
  onAuthSuccess,
}) => {
  const [showLogin, setShowLogin] = useState(true);

  const switchToLogin = () => setShowLogin(true);
  const switchToRegister = () => {
    console.log("switchToRegister appelé");
    setShowLogin(false);
    console.log("Nouvel état showLogin:", false);
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-900 p-4">
      <div className="w-full max-w-md">
        {showLogin ? (
          <Login
            onLoginSuccess={onAuthSuccess}
            onRegisterClick={switchToRegister}
          />
        ) : (
          <Register
            onRegisterSuccess={switchToLogin}
            onLoginClick={switchToLogin}
          />
        )}
      </div>
    </div>
  );
};

export default AuthContainer;

// angular/src/app/components/auth/auth-container/auth-container.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LoginComponent } from '../login/login.component';
import { RegisterComponent } from '../register/register.component';

@Component({
  selector: 'app-auth-container',
  standalone: true,
  imports: [CommonModule, LoginComponent, RegisterComponent],
  template: `
    <div class="min-h-screen flex items-center justify-center bg-gray-900 p-4">
      <div class="w-full max-w-md">
        <ng-container *ngIf="showLogin; else registerTemplate">
          <app-login
            (onLoginSuccess)="onAuthSuccess()"
            (onRegisterClick)="switchToRegister()"
          ></app-login>
        </ng-container>

        <ng-template #registerTemplate>
          <app-register
            (onRegisterSuccess)="switchToLogin()"
            (onLoginClick)="switchToLogin()"
          ></app-register>
        </ng-template>
      </div>
    </div>
  `,
  styles: [],
})
export class AuthContainerComponent {
  showLogin = true;

  switchToLogin() {
    this.showLogin = true;
  }

  switchToRegister() {
    this.showLogin = false;
  }

  onAuthSuccess() {
    // Cette méthode sera remplacée par le composant parent qui l'utilise
    console.log('Authentification réussie!');
  }
}
