// react/src/components/auth/login.tsx
import React, { useState } from "react";
import { apiService } from "../../services/api-service";

interface LoginProps {
  onLoginSuccess: () => void;
  onRegisterClick: () => void;
}

export const Login: React.FC<LoginProps> = ({
  onLoginSuccess,
  onRegisterClick,
}) => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError("");

    try {
      const success = await apiService.login(username, password);
      if (success) {
        onLoginSuccess();
      } else {
        setError("Nom d'utilisateur ou mot de passe incorrect");
      }
    } catch (err: any) {
      setError(err.message || "Une erreur s'est produite lors de la connexion");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col items-center justify-center bg-gray-900 text-white p-8 rounded-lg shadow-lg w-full max-w-md mx-auto mt-10">
      <h1 className="text-3xl font-bold mb-6">Connexion</h1>

      {error && (
        <div className="w-full bg-red-600 text-white p-3 rounded mb-4 text-center">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit} className="w-full">
        <div className="mb-4">
          <label htmlFor="username" className="block text-sm font-medium mb-1">
            Nom d'utilisateur
          </label>
          <input
            type="text"
            id="username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            className="w-full p-3 rounded bg-gray-800 border border-gray-700 focus:border-blue-500 focus:outline-none text-white"
            required
          />
        </div>

        <div className="mb-6">
          <label htmlFor="password" className="block text-sm font-medium mb-1">
            Mot de passe
          </label>
          <input
            type="password"
            id="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className="w-full p-3 rounded bg-gray-800 border border-gray-700 focus:border-blue-500 focus:outline-none text-white"
            required
          />
        </div>

        <button
          type="submit"
          disabled={isLoading}
          className={`w-full p-3 rounded font-medium ${
            isLoading
              ? "bg-blue-700 cursor-not-allowed"
              : "bg-blue-600 hover:bg-blue-700"
          } transition`}
        >
          {isLoading ? "Connexion en cours..." : "Se connecter"}
        </button>
      </form>

      <div className="mt-6 text-center">
        <p className="text-gray-400">
          Pas encore de compte ?{" "}
          <button
            onClick={(e) => {
              console.log("Bouton 'Créer un compte' cliqué");
              onRegisterClick();
            }}
            className="text-blue-400 hover:text-blue-300 cursor-pointer"
          >
            Créer un compte
          </button>
        </p>
      </div>
    </div>
  );
};

export default Login;

// angular/src/app/components/auth/login/login.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../services/api.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div
      class="flex flex-col items-center justify-center bg-gray-900 text-white p-8 rounded-lg shadow-lg w-full max-w-md mx-auto mt-10"
    >
      <h1 class="text-3xl font-bold mb-6">Connexion</h1>

      <div
        *ngIf="error"
        class="w-full bg-red-600 text-white p-3 rounded mb-4 text-center"
      >
        {{ error }}
      </div>

      <form (ngSubmit)="handleSubmit()" class="w-full">
        <div class="mb-4">
          <label for="username" class="block text-sm font-medium mb-1">
            Nom d'utilisateur
          </label>
          <input
            type="text"
            id="username"
            [(ngModel)]="username"
            name="username"
            class="w-full p-3 rounded bg-gray-800 border border-gray-700 focus:border-blue-500 focus:outline-none text-white"
            required
          />
        </div>

        <div class="mb-6">
          <label for="password" class="block text-sm font-medium mb-1">
            Mot de passe
          </label>
          <input
            type="password"
            id="password"
            [(ngModel)]="password"
            name="password"
            class="w-full p-3 rounded bg-gray-800 border border-gray-700 focus:border-blue-500 focus:outline-none text-white"
            required
          />
        </div>

        <button
          type="submit"
          [disabled]="isLoading"
          class="w-full p-3 rounded font-medium"
          [ngClass]="
            isLoading
              ? 'bg-blue-700 cursor-not-allowed'
              : 'bg-blue-600 hover:bg-blue-700'
          "
        >
          {{ isLoading ? 'Connexion en cours...' : 'Se connecter' }}
        </button>
      </form>

      <div class="mt-6 text-center">
        <p class="text-gray-400">
          Pas encore de compte ?
          <button
            (click)="onRegisterClick.emit()"
            class="text-blue-400 hover:text-blue-300 cursor-pointer"
          >
            Créer un compte
          </button>
        </p>
      </div>
    </div>
  `,
  styles: [],
})
export class LoginComponent {
  @Output() onLoginSuccess = new EventEmitter<void>();
  @Output() onRegisterClick = new EventEmitter<void>();

  username: string = '';
  password: string = '';
  error: string = '';
  isLoading: boolean = false;

  constructor(private apiService: ApiService) {}

  async handleSubmit() {
    if (!this.username || !this.password) {
      this.error = 'Veuillez remplir tous les champs';
      return;
    }

    this.isLoading = true;
    this.error = '';

    try {
      const success = await this.apiService
        .login(this.username, this.password)
        .toPromise();
      if (success) {
        this.onLoginSuccess.emit();
      } else {
        this.error = "Nom d'utilisateur ou mot de passe incorrect";
      }
    } catch (err: any) {
      this.error =
        err.message || "Une erreur s'est produite lors de la connexion";
    } finally {
      this.isLoading = false;
    }
  }
}
